### PR TITLE
Use Prout as superclass instead of Proutine

### PR DESCRIPTION
**Pull request by jpburstrom**
This fixes broken language compilation in 3.8

### CODE REVIEW

**Comment by nhthn** [comment]
This repository is not maintained anymore -- you're looking for https://github.com/jamshark70/ddwChucklib. This is a sign that your copy of the quarks directory is out of date.

**Comment by jpburstrom** [comment]
Oh, sorry. In fact I have a local copy of the jamshark70/ddwChucklib repository, I just somehow made a pull request on the wrong repo. I'll close this and make a new one over there.

**Comment by nhthn** [comment]
@jamshark70 What should we do with this repository?

**Comment by jamshark70** [comment]
> What should we do with this repository?

I don't know -- @crucialfelix, do we have a standard practice for these repositories, after the original author forked? IMO best is to delete repositories under supercollider-quarks/ when they are no longer in the quarks index.

**Comment by nhthn** [comment]
I suggest we blank it with a README that says "this repository has moved"

**Comment by crucialfelix** [comment]
I deleted one the other day on request from the author.  So I say we just delete them.

Not worth adding any extra labor IMO.

**Pull request closed without merging**
